apiVersion: v1
kind: Service
metadata:
  name: ui-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0296850f8bbdb4071,subnet-0f48cea7605a82a38
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
